### ISSUE TITLE
BLACK_LIST

### ISSUE THREAD

**Issue by hktalent** [hktalent/CVE_2020_2546#2]
DEFAULT_BLACK_LIST = "+org.apache.commons.collections.functors,+com.sun.org.apache.xalan.internal.xsltc.trax,+javassist,+org.codehaus.groovy.runtime.ConvertedClosure,+org.codehaus.groovy.runtime.ConversionHandler,+org.codehaus.groovy.runtime.MethodClosure,+org.springframework.transaction.support.AbstractPlatformTransactionManager";

DEFAULT_BLACKLIST_PACKAGES = { "org.apache.commons.collections.functors", "com.sun.org.apache.xalan.internal.xsltc.trax", "javassist", "java.rmi.activation", "sun.rmi.server", "com.bea.core.repackaged.springframework.beans.factory.support", "org.python.core" };

DEFAULT_BLACKLIST_CLASSES = { "org.codehaus.groovy.runtime.ConvertedClosure", "org.codehaus.groovy.runtime.ConversionHandler", "org.codehaus.groovy.runtime.MethodClosure", "org.springframework.transaction.support.AbstractPlatformTransactionManager", "java.rmi.server.UnicastRemoteObject", "java.rmi.server.RemoteObjectInvocationHandler", "com.bea.core.repackaged.springframework.transaction.support.AbstractPlatformTransactionManager", "java.rmi.server.RemoteObject", "java.lang.Runtime", "com.tangosol.coherence.rest.util.extractor.MvelExtractor" };

**Comment by Y4er** [comment]
com.tangosol.util.extractor.MultiExtractor#extract thinks.
